version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:864965617905:task-definition/lkg-class-book-manager:1" 
        LoadBalancerInfo:
          ContainerName: "book-manager"
          ContainerPort: 8080
